// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVUCJQGue8iAoZHqdx_d1NfD7970Ypcpw',
    appId: '1:813470368358:web:a0ae3f3342fbdf072463a7',
    messagingSenderId: '813470368358',
    projectId: 'nnfiub-mobile',
    authDomain: 'nnfiub-mobile.firebaseapp.com',
    storageBucket: 'nnfiub-mobile.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWI8S0yTCX4d-wUuChuHTegfbyO27p3PU',
    appId: '1:813470368358:android:a7da5d1ea20b20da2463a7',
    messagingSenderId: '813470368358',
    projectId: 'nnfiub-mobile',
    storageBucket: 'nnfiub-mobile.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCr41VGxOyKgEcIAxLNVkFL9-umTFzwLY0',
    appId: '1:813470368358:ios:83f1cfcf4ddaf98a2463a7',
    messagingSenderId: '813470368358',
    projectId: 'nnfiub-mobile',
    storageBucket: 'nnfiub-mobile.firebasestorage.app',
    iosBundleId: 'com.example.finalProjectMobileApp',
  );
}
